CREATE TABLE person(
                       id BIGINT GENERATED BY DEFAULT as identity PRIMARY KEY,
                       name varchar,
                       surname varchar,
                       patronymic varchar,
                       birthDate DATE,
                       gender varchar
);

CREATE TABLE document(
                         id int GENERATED BY DEFAULT as identity PRIMARY KEY,
                         series varchar NOT NULL,
                         number varchar NOT NULL,
                         type varchar NOT NULL,
                         issueDate DATE NOT NULL,
                         person_id BIGINT NOT NULL,
                         FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE answer_xml(
    id int GENERATED BY DEFAULT as identity PRIMARY KEY,
    xml TEXT NOT NULL,
    person_id BIGINT NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE
);